solved the issue mentioned in #174
flutter/udacity-course pull request #175
Opened 2020-06-06 16:14 UTC by AneshkaGoyal

I have solved the issue opened as #174

2020-06-06 16:19 UTC, AneshkaGoyal commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fflutter%2Fudacity-course%2Fpull%2F175) for more info**.

@googlebot I signed it!

2020-06-10 05:38 UTC, AneshkaGoyal commented
Hey 
Please have a look at the pull request raised @ianloic @gmoothart @sethladd

2020-06-19 05:41 UTC, AneshkaGoyal commented
@googlebot please review pull request

2020-08-19 20:09 UTC, maryx commented
Hi @AneshkaGoyal! Thank you for your patience. Can you please run dartfmt on the file?

2021-05-31 04:51 UTC, domesticmouse commented on course/12_error/solution_12_error/lib/category_route.dart
> +            c.name == apiCategory['name'] && c.units.isEmpty
I suspect this logic should be integrated into `_onCategoryTap`

2021-05-31 04:52 UTC, domesticmouse requested changes
Splitting logic between the `onTap` handler and the callback is kinda messy. Please integrate.

2021-09-21 08:17 UTC, merged